### ISSUE TITLE
增加 --msg

### ISSUE THREAD

**Issue by atian25** [fex-team/fis-command-release#16]
以便deploy到服务端的时候, 可以传递注释消息给服务端

**Comment by 2betop** [comment]
具体点，是说希望显示服务端的内容返回吗？目前只显示状态值。

**Comment by atian25** [comment]
其实还是因为`commander`限制太死了,  我写了一个deploy插件, post到我的服务器, 但需要同时加一点注释, 如:  `scrat release -d remote --msg=test` , 但目前`release`插件里面不支持这个参数, 所以传递不过去

**Comment by atian25** [comment]
刚发现 commander 有个 `allowUnknown()`
https://github.com/tj/commander.js/pull/310/files

**Comment by xiangshouding** [comment]
@atian25 这个我得说两句，这个跟限定死没啥关系，限定死必定有限定死的好处，假设不限定死那么数错命令也不知道，而且很容易造成问题井喷的情况，很多人都会由于没有设置正确的参数而吐槽。

所以，对于这种抉择可能更好的方式是检测已知的，而对未知进行 warning。

**Comment by atian25** [comment]
我的想法是这样的:  `目前fis的插件机制, 很难在原有插件上增加额外功能, 只能开发者暴露接口或者fork后自己改`.

对于`commander`的这个, 我建议增加`allowUnknown()`, 然后fis来一个warning就ok了, 并把unknown的数据往后丢, 而不是直接error.

**Comment by fouber** [comment]
这里 @atian25 并不是要显示信息，而是要提交一些请求参数给服务器，这样接收端receiver可以根据这些参数判断如何接收文件。不过这个目前还没有办法通过命令行传递，因为commander不支持未知参数的读取

具体的实现思路应该是把这个参数通过 ``fis-conf.js`` 中的settings传递给插件，插件post的时候负责提交这些信息，比如：

```js
...
fis.config.set('settings.deploy.remote.msg', process.env.POST_MESSAGE || 'default message');
...
```

然后你可以

```bash
scrat release -d remote
```

或者：

```bash
POST_MESSAGE= test scrat release -d remote
```

**Comment by atian25** [comment]
云龙，comannder已经有个allowUnknown

**Comment by atian25** [comment]
POST_MESSAGE=test scrat release -d remote 这种方式还是蛮违反直觉的
