### ISSUE TITLE
多次读取项目配置的文本文件会造成crash

### ISSUE THREAD

**Issue by yanni4night** [fex-team/fis-command-release#8]
[第86行](https://github.com/fex-team/fis-command-release/blob/a4653b8894dcedaa2ad1b74d8a22c7088ef57931/lib/deploy.js#L86) 这里是不是要转成字符串呢，因为 `fis.util.toEncoding()` 返回的是 `Buffer`对象，而这片代码是在 _file.isText()_ 分支下的。

遇到过在新机器上部署 `fis` ，有些文本文件是被 `fis` 多次读取的，一个文本文件的 _content_ 一旦被设置为 `Buffer` 对象后，下次读取可能会假设其为 `String` 而直接调用 _replace_ 方法最终 crash。

```
/usr/local/lib/node_modules/fis/node_modules/fis-command-release/lib/deploy.js:65
                content = content.replace(reg, dest.replace.to);
                                  ^
TypeError: Object <?
$this->display("activity_head/activity_head.php");
?>
 has no method 'replace'
    at prepareDeploy (/usr/local/lib/node_modules/fis/node_modules/fis-command-release/lib/deploy.js:65:35)
```

**Comment by xiangshouding** [comment]
确实需要做兼容，你提个 pr 过来。

**Comment by xiangshouding** [comment]
`toEncoding` 应该返回 `string`，不然整个从逻辑上就有问题了。正在看`iconv-lite`是否支持`toString`某一个特定编码。

**Comment by hefangshi** [comment]
这里不能用字符的，只能是二进制流，类似的问题我有遇到过

https://github.com/fex-team/fis-command-release/commit/24b55dc7ecd1af338c8f9eda6e47f9e772e0f5d5#diff-eff50028862616c28af389bc1a879f9bR89

你上次修复的时候加的这句话导致的这个问题，不能setContent，因为每个release的replace都是独立的，不应该记录在文件中，所以接口才会把file和content分开传入

**Comment by xiangshouding** [comment]
本身 `string` 被搞成了 `buffer`，本身从逻辑上就有问题，这算是一个坑，而且这个坑很容易踩到。

**Comment by yanni4night** [comment]
`fis.util.read()` 对非 `utf8` 编码的文本文件返回 `Buffer` 对象而非 `String` 应该是因为 `nodejs` 本身就无法直接表示 _GBK_ 的字符串吧。

**Comment by xiangshouding** [comment]
@yanni4night 嗯，是的。所以要借助外部库来实现。可想，这块确实挺坑。

**Comment by xiangshouding** [comment]
@hefangshi 现在这种实现下，`replace` 的过程会被一遍又一遍的过？比如我经过俩 `deploy`？我没有尝试过放多个 `deploy` 的情况。

**Comment by hefangshi** [comment]
@xiangshouding 是的，因为每个deploy都有独立的replace设置，所以每个deploy都需要独立的进行replace，并且由于Javascript中的字面量也只有UTF8编码格式，因此编码转换也必须每次独立执行，才能进行正确的replace。

这个issue的触发原因实际上也是release了两个以上的deploy，并且编码是GBK导致的。我上次做deploy插件化也踩了一模一样的坑，直接setContent了，是贴吧的同学反馈的。

**Comment by xiangshouding** [comment]
嗯，好的，我先暂且删掉修复一把。

**Comment by yanni4night** [comment]
[#diff-eff50028862616c28af389bc1a879f9bR55](https://github.com/fex-team/fis-command-release/commit/24b55dc7ecd1af338c8f9eda6e47f9e772e0f5d5#diff-eff50028862616c28af389bc1a879f9bR55) 这里进入判断分支的时候如果charset不是utf8的话content理论上一定是 `Buffer` ,是不是还有crash的危险

**Comment by hefangshi** [comment]
不setContent的话是没问题的
